test_that("README documents the current collaborator handoff artifacts", {
    readme <- paste(readLines(file.path(repo_root, "README.md"), warn = FALSE), collapse = "\n")
    docs_readme <- paste(readLines(file.path(repo_root, "docs", "README.md"), warn = FALSE), collapse = "\n")

    expect_match(readme, "comparison_workbook\\.xlsx")
    expect_match(readme, "run_index\\.tsv")
    expect_match(readme, "methods_overview\\.md")
    expect_match(readme, "select_analytes/")
    expect_match(readme, "barplots/<method>/all_tested/")
    expect_match(readme, "barplots/<method>/significant_hits/<threshold>/")
    expect_match(readme, "input_qc/reference_spot_qc.tsv", fixed = TRUE)
    expect_match(readme, "Selected analytes are optional")

    expect_match(docs_readme, "comparison_workbook\\.xlsx")
    expect_match(docs_readme, "run_index\\.tsv")
    expect_match(docs_readme, "barplots/<method>/all_tested/")
    expect_match(docs_readme, "barplots/<method>/significant_hits/<threshold>/")
    expect_match(docs_readme, "input_qc/reference_spot_qc.tsv", fixed = TRUE)
    expect_match(docs_readme, "Selected-analyte outputs are optional")
})

test_that("documentation explains replicate-aware barplot scale and SE construction", {
    readme <- paste(readLines(file.path(repo_root, "README.md"), warn = FALSE), collapse = "\n")
    docs_readme <- paste(readLines(file.path(repo_root, "docs", "README.md"), warn = FALSE), collapse = "\n")
    method_note <- paste(readLines(file.path(repo_root, "docs", "method-comparison-worked-example.md"), warn = FALSE), collapse = "\n")

    expect_match(readme, "linear fold-change-ratio y-axis")
    expect_match(readme, "normalized_signal = averaged duplicate raw analyte signal / sample reference-spot denominator", fixed = TRUE)
    expect_match(readme, "preferred Reference Spots pairs `A1,2` and `J1,2`", fixed = TRUE)
    expect_match(readme, "exact reference rows and raw reference signals", fixed = TRUE)
    expect_match(readme, "creates `low_signal_flag` for every configured method", fixed = TRUE)
    expect_match(readme, "does not remove analytes before p-value adjustment", fixed = TRUE)
    expect_match(readme, "visual group-mean SE bars")
    expect_match(readme, "Waterfall whiskers")
    expect_match(docs_readme, "linear fold-change-ratio y-axis")
    expect_match(docs_readme, "per-sample `normalized_signal`", fixed = TRUE)
    expect_match(docs_readme, "normalized_t_test")
    expect_match(docs_readme, "raw_log2_lm")
    expect_match(docs_readme, "low_signal_flag` for every replicate-aware method", fixed = TRUE)
    expect_match(method_note, "`normalized_signal` as averaged duplicate raw analyte signal divided by that sample's reference-spot denominator", fixed = TRUE)
    expect_match(method_note, "`low_signal_flag` for every configured method", fixed = TRUE)
    expect_match(method_note, "SE\\(control-arm normalized_signal values\\) / mean\\(control-arm normalized_signal values\\)")
    expect_match(method_note, "2\\^\\(effect_estimate_log2 \\+/- SE\\(treatment log2 values\\)\\)")
    expect_match(method_note, "not confidence intervals for the treatment-vs-control contrast")
})
